#!/usr/bin/env python3
"""
FNS Dogleg Duct Streaming Experiment -- Geometry Visualization
===============================================================

Produces cross-section plots of the FNS dogleg duct experiment:

  1. XZ cross-section at y=0 -- shows the full dogleg duct path through the
     iron assembly (the most informative view, as the duct bends lie in the
     XZ plane).

  2. XY cross-section at z=0 -- shows the 1st horizontal duct leg entering
     the iron assembly (horizontal slice through the first leg).

  3. XY cross-section at z=60 cm -- shows the 2nd horizontal duct leg
     (horizontal slice through the second leg, offset vertically).

Usage:
    python visualize.py

Requires:
    materials.xml, geometry.xml (generated by model.py)

Output:
    fns_dogleg_xz.png   -- side view showing dogleg path
    fns_dogleg_xy_z0.png -- plan view at z=0 (1st leg)
    fns_dogleg_xy_z60.png -- plan view at z=60 cm (2nd leg)
"""

import openmc


def main():
    # =========================================================================
    # Load geometry and materials from XML files
    # =========================================================================
    materials = openmc.Materials.from_xml("materials.xml")
    geometry = openmc.Geometry.from_xml("geometry.xml", materials=materials)

    # Custom colour map: iron in steel-blue, void in white
    color_map = {}
    for mat in materials:
        if "Iron" in mat.name or "iron" in mat.name:
            color_map[mat] = (70, 130, 180)   # steel blue for iron

    plots = openmc.Plots()

    # =========================================================================
    # Plot 1: XZ cross-section at y=0 (side view -- shows the dogleg)
    # =========================================================================
    # This is the key view: it shows the full dogleg duct path through the
    # iron assembly. The 1st horizontal leg, the vertical leg, and the 2nd
    # horizontal leg are all visible in this plane.
    plot_xz = openmc.Plot()
    plot_xz.filename = "fns_dogleg_xz"
    plot_xz.basis = "xz"
    plot_xz.origin = (85.0, 0.0, 15.0)       # centre of view (approx assembly midpoint)
    plot_xz.width = (220.0, 220.0)            # field of view in cm
    plot_xz.pixels = (1100, 1100)             # image resolution
    plot_xz.color_by = "material"
    plot_xz.colors = color_map
    plots.append(plot_xz)

    # =========================================================================
    # Plot 2: XY cross-section at z=0 (plan view -- 1st horizontal leg)
    # =========================================================================
    # Horizontal slice through the centre of the 1st duct leg. Shows the
    # duct entrance on the front face and the leg extending into the iron.
    plot_xy_z0 = openmc.Plot()
    plot_xy_z0.filename = "fns_dogleg_xy_z0"
    plot_xy_z0.basis = "xy"
    plot_xy_z0.origin = (85.0, 0.0, 0.0)     # z=0 (centre of 1st leg)
    plot_xy_z0.width = (220.0, 180.0)
    plot_xy_z0.pixels = (1100, 900)
    plot_xy_z0.color_by = "material"
    plot_xy_z0.colors = color_map
    plots.append(plot_xy_z0)

    # =========================================================================
    # Plot 3: XY cross-section at z=60 cm (plan view -- 2nd horizontal leg)
    # =========================================================================
    # Horizontal slice through the centre of the 2nd duct leg. Shows the
    # offset horizontal leg at the top of the dogleg.
    plot_xy_z60 = openmc.Plot()
    plot_xy_z60.filename = "fns_dogleg_xy_z60"
    plot_xy_z60.basis = "xy"
    plot_xy_z60.origin = (85.0, 0.0, 60.0)   # z=60 cm (centre of 2nd leg)
    plot_xy_z60.width = (220.0, 180.0)
    plot_xy_z60.pixels = (1100, 900)
    plot_xy_z60.color_by = "material"
    plot_xy_z60.colors = color_map
    plots.append(plot_xy_z60)

    # =========================================================================
    # Export and generate plots
    # =========================================================================
    plots.export_to_xml()
    openmc.plot_geometry()

    print("Geometry plots saved:")
    print("  fns_dogleg_xz.png      -- XZ side view (shows full dogleg duct path)")
    print("  fns_dogleg_xy_z0.png   -- XY plan view at z=0 (1st horizontal leg)")
    print("  fns_dogleg_xy_z60.png  -- XY plan view at z=60 cm (2nd horizontal leg)")


if __name__ == "__main__":
    main()
